Stop event bubbling for navigation arrows
vtex-apps/shelf pull request #244
Opened 2020-10-30 12:22 UTC by oviolion

#### What problem is this solving?
Navigation arrows would not work when the `slider` was placed inside an `<a>` tag. This is the case if you were to place a `slider` inside of a `product-summary`. In our case, the `related-products` shelf is using the deprecated version of the slider.

#### How to test it?

[Workspace](https://createbundle--fstudioqa.myvtex.com/aparate-foto/aparate-foto-dslr/aparate-foto-dslr-profesionisti?map=departament,categorie,subcategorie)

#### Screenshots or example usage:
Before:
![Before](https://user-images.githubusercontent.com/68231117/97704446-121c8e80-1abb-11eb-96af-1b0edb2de41b.gif)

After:
![After](https://user-images.githubusercontent.com/68231117/97704458-16e14280-1abb-11eb-8335-e60b220f49b6.gif)

2020-11-03 19:37 UTC, klzns requested changes
Thanks for the pull request! Just a minor lint issue

2020-11-03 19:37 UTC, klzns commented on react/components/ShelfContent.js
> +                <ShelfItem item={item} summary={summary}/>
```suggestion
                <ShelfItem item={item} summary={summary} />
```

2020-11-04 14:32 UTC, klzns approved these changes

2020-11-04 14:40 UTC, kaisermann approved these changes

2020-11-04 14:40 UTC, victorhmp commented
@oviolion Everything looks good!
Just out of curiosity, why do you need this implemented in this app since this was already added to the `slider-layout` app? 

I ask because this app is deprecated, so I suggest you use the `slider-layout` in your theme.

2020-11-04 14:48 UTC, oviolion commented
> @oviolion Everything looks good!
> Just out of curiosity, why do you need this implemented in this app since this was already added to the `slider-layout` app?
> 
> I ask because this app is deprecated, so I suggest you use the `slider-layout` in your theme.

It is because the `vtex.shelf` component is still using this deprecated version of the slider and some of our components are still using the shelf component

2020-11-04 14:56 UTC, victorhmp commented
> > @oviolion Everything looks good!
> > Just out of curiosity, why do you need this implemented in this app since this was already added to the `slider-layout` app?
> > I ask because this app is deprecated, so I suggest you use the `slider-layout` in your theme.
> 
> It is because the `vtex.shelf` component is still using this deprecated version of the slider and some of our components are still using the shelf component

Okay :)

2020-11-04 16:58 UTC, merged